package Genex.entities;

import java.time.LocalDateTime;

public class TournamentMatch {

    private String id;
    private String tournamentId;
    private String challongeMatchId;
    private int round;
    private int matchNumber;
    private String player1Id;
    private String player2Id;
    private String winnerId;
    private int player1Score;
    private int player2Score;
    private MatchStatus status;
    private LocalDateTime scheduledTime;
    private LocalDateTime completedTime;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public enum MatchStatus {
        PENDING("En attente"),
        IN_PROGRESS("En cours"),
        COMPLETED("Terminé");

        private final String displayName;

        MatchStatus(String displayName) {
            this.displayName = displayName;
        }

        public String getDisplayName() {
            return displayName;
        }
    }

    // Constructors
    public TournamentMatch() {
        // ID will be auto-generated by database
        this.status = MatchStatus.PENDING;
        this.player1Score = 0;
        this.player2Score = 0;
    }

    public TournamentMatch(String tournamentId, int round, int matchNumber) {
        this();
        this.tournamentId = tournamentId;
        this.round = round;
        this.matchNumber = matchNumber;
    }

    // Helper methods
    public boolean isCompleted() {
        return status == MatchStatus.COMPLETED;
    }

    public boolean hasWinner() {
        return winnerId != null && !winnerId.isEmpty();
    }

    public String getMatchLabel() {
        return "Round " + round + " - Match " + matchNumber;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTournamentId() {
        return tournamentId;
    }

    public void setTournamentId(String tournamentId) {
        this.tournamentId = tournamentId;
    }

    public String getChallongeMatchId() {
        return challongeMatchId;
    }

    public void setChallongeMatchId(String challongeMatchId) {
        this.challongeMatchId = challongeMatchId;
    }

    public int getRound() {
        return round;
    }

    public void setRound(int round) {
        this.round = round;
    }

    public int getMatchNumber() {
        return matchNumber;
    }

    public void setMatchNumber(int matchNumber) {
        this.matchNumber = matchNumber;
    }

    public String getPlayer1Id() {
        return player1Id;
    }

    public void setPlayer1Id(String player1Id) {
        this.player1Id = player1Id;
    }

    public String getPlayer2Id() {
        return player2Id;
    }

    public void setPlayer2Id(String player2Id) {
        this.player2Id = player2Id;
    }

    public String getWinnerId() {
        return winnerId;
    }

    public void setWinnerId(String winnerId) {
        this.winnerId = winnerId;
    }

    public int getPlayer1Score() {
        return player1Score;
    }

    public void setPlayer1Score(int player1Score) {
        this.player1Score = player1Score;
    }

    public int getPlayer2Score() {
        return player2Score;
    }

    public void setPlayer2Score(int player2Score) {
        this.player2Score = player2Score;
    }

    public MatchStatus getStatus() {
        return status;
    }

    public void setStatus(MatchStatus status) {
        this.status = status;
    }

    public LocalDateTime getScheduledTime() {
        return scheduledTime;
    }

    public void setScheduledTime(LocalDateTime scheduledTime) {
        this.scheduledTime = scheduledTime;
    }

    public LocalDateTime getCompletedTime() {
        return completedTime;
    }

    public void setCompletedTime(LocalDateTime completedTime) {
        this.completedTime = completedTime;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return "TournamentMatch{" +
                "id='" + id + '\'' +
                ", tournamentId='" + tournamentId + '\'' +
                ", round=" + round +
                ", matchNumber=" + matchNumber +
                ", player1Id='" + player1Id + '\'' +
                ", player2Id='" + player2Id + '\'' +
                ", winnerId='" + winnerId + '\'' +
                ", status=" + status +
                '}';
    }
}
